name: "CI & CD"
on:
  push:
    tags:
      - '*'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 20
          distribution: zulu
      - name: Build & Deploy
        uses: gradle/gradle-build-action@v2.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IS_RELEASE_BUILD: true
        with:
          gradle-version: 8.2.1
          arguments: clean test build publish  --stacktrace
      - name: Upload Test Results
        uses: dorny/test-reporter@v1.6.0
        if: success() || failure()
        with:
          name: Test Results
          path: build/test-results/test/*.xml
          reporter: java-junit
